language: ruby
rvm:
  - 2.5
script: bundle exec jekyll build
cache: bundler

branches:
  only:
      - master
deploy:
  provider: script
  #script: gem install aliyun-sdk && ruby scripts/deploy.rb
  script: bundle exec jekyll deploy
  on:
    branch: master 

notifications:
  email: false
